### ISSUE TITLE
"Make a Party"

### ISSUE THREAD

**Issue by dpaiv0** [SpotiParty/api#1]
## Overview
The user creating this will be called the DJ, and the members of that party will be called, well, members.
The party will have a 10-digit number attributed to it, as with an option for the user to input a password (or not - it's optional!)
Also, the party should have a queue system (alloying to see and edit what's going to be played), alongisde moderation options for the DJ (kick, ban) and a share function, without exposing the PIN (allowing for it to be a one-time use invite link or a multiple-time use one.)

## Roadmap

- [ ] Create the database and its models _(Party: Name, Id, Password (optional), [ Queue ], [ Members ]...)_ 
- [ ] Generate a unique 10-digit number to that party, to avoid conflicts between other parties (0.0000000001% chance of happening, but still possible.)
- [ ] Security System (password? 4-6 digit PIN?) (optional)
- [ ] Queue System (add songs, edit song position (DJ), delete song (self member or DJ))
- [ ] Now Playing (e.g. [Aiden Wallis' Spotify Widget for Streamlabs](https://i.imgur.com/HDyqBx6.png))
- [ ] Share the Party (without exposing the password / PIN (maybe with [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken)?) and making it one-time or multiple-time use.)

**Comment by metehus** [comment]
remember to make a URl, for example https://join.spotiparty.tech/hrNwgEZe93kWFGg

**Comment by metehus** [comment]
another tip: use the party creator's song queue from spotify as a pre-load

**Comment by dpaiv0** [comment]
nice suggestions, @metehus! will add them to the roadmap
