### ISSUE TITLE
"Join a Party"

### ISSUE THREAD

**Issue by dpaiv0** [SpotiParty/api#2]
## Overview
Same concept as #1, but instead of creating, join an existing one.
The user here will be able to add songs to the queue, and also remove songs it added.
## Roadmap
- [ ] Verify if the party ID is valid (and active)
- [ ] Verify that the password is correct
- [ ] Make queue system
